# Generated by Django 5.0.1 on 2024-03-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('e_mail', models.CharField(max_length=200)),
                ('pass_word', models.CharField(max_length=200)),
            ],
        ),
    ]
